# coding: utf-8

"""
    Allele Calling Service

    The Allele Calling  service provides an API for converting raw sequence data to GFE and HLA allele calls.  # noqa: E501

    OpenAPI spec version: 0.0.5
    Contact: mhalagan@nmdp.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import gfe_client
from gfe_client.models.typing import Typing  # noqa: E501
from gfe_client.rest import ApiException


class TestTyping(unittest.TestCase):
    """Typing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTyping(self):
        """Test Typing"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.typing.Typing()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
